name: web_socket_chat
description: "A simple web socket chat application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  http: ^1.2.2
  injectable: ^2.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
